### ISSUE TITLE
Seaborn to discontinue distplot

### ISSUE THREAD

**Issue by tfuger10** [learn-co-curriculum/dsc-probability-density-function#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
THe distplot function is going to be discontinued by seaborn in the future, so it should just be taken out of this lesson
```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
addressing with multiple repos. I am closing this at this time.
