### ISSUE TITLE
None of the Saturn cloud links are launching successfully 

### ISSUE THREAD

**Issue by steve-gomes** [learn-co-curriculum/dsc-probability-density-function#2]
"Click Here to Launch Lesson" takes me to the Saturn Cloud Login "continue with flatiron-school" link which takes me to Canvas "Authorize" link, which then resolves to an error on Saturn Cloud side:

{"message": "Page not found."}

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Hi @steve-gomes thanks for opening this issue with us :wave:. Have you been able to use Saturn Cloud before you tried launching from the links last week?

If so, is there any way you can drop the URL to the page that is returning the `{"message": "Page not found."}` error?

**Comment by steve-gomes** [comment]
Good news it looks like Saturn Cloud links are working now
They must have had some downtime over the long holiday weekend

You can close this issue then

thanks
Steve
