### ISSUE TITLE
INCOMPLETE INFO

### ISSUE THREAD

**Issue by JoyKarey** [learn-co-curriculum/dsc-probability-density-function#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by JoyKarey** [comment]
The info in that lab is so scanty, and its just code without any explanation!

**Comment by jessepisel** [comment]
thank you for opening this issue :wave:. Please fill out the form with more information. If this is for the probability density function lab please open an issue there with your recommendations for what you would like to see to improve the lab. I am closing this issue at this time.
