### ISSUE TITLE
NOTEBOOK NOT LOADING PROPERLY

### ISSUE THREAD

**Issue by KarimiNyaga** [learn-co-curriculum/dsc-probability-density-function#4]
## Link to Canvas

https://moringa.instructure.com/courses/474/assignments/31441?module_item_id=67208

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [X ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
Notebook failing to load markdown cells where information about the lesson is. Title also doesn't align with lesson. I
Title reads as "image_generator"
```

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue :wave:. I have updated the link to the `index.ipynb` file. It works on both Saturn Cloud and locally as well.
