### ISSUE TITLE
The Probability Density Function (PDF)

### ISSUE THREAD

**Issue by scarlettvalentin** [learn-co-curriculum/dsc-probability-density-function#5]
## Link to Canvas

https://learning.flatironschool.com/courses/7297/assignments/270641?module_item_id=651360

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
The bottom of the lesson states "This looks pretty good! In the next lab, you'll practice your knowledge!" There is no lab following this lesson in Canvas. I don't think this section is uploaded correctly.
```

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for flagging this, we'll take a look.

**Comment by bpurdy-ds** [comment]
Fixed. Thanks again for the suggestion.

**Comment by scarlettvalentin** [comment]
Thank you for the prompt response!

--

*Scarlett Valentin*
